# Set nginx base image
FROM nginx:alpine-perl

LABEL maintainer="Hantsy Bai"

EXPOSE 80

# RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf

COPY ./client/dist /usr/share/nginx/html 


